### ISSUE TITLE
Error under Flutter 3.19

### ISSUE THREAD

**Issue by christophe-andre** [john-rager/mika_treeview#19]
lib/src/tree_search.dart:82:17

   ╷
82 │                 primary: theme.colorScheme.onPrimary,
   │                 ^^^^^^^
   ╵

**Comment by john-rager** [comment]
Hi Christophe - thanks for catching that!  Should be all set now.

**Comment by christophe-andre** [comment]
Hi John,

Thanks you. I will try later.

Best regards from France ;-)

Le mar. 12 mars 2024 à 21:09, John Rager ***@***.***> a
écrit :
